export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SETKEYWORD='SETKEYWORD';
export const SETWRITTENBY='SETWRITTENBY';
export const SETYEARFROM='SETYEARFROM';
export const SETYEARTO='SETYEARTO';
export const SETPUBLICATIONTYPE='SETPUBLICATIONTYPE';
export const SETAUTHORORDER='SETAUTHORORDER';
export const SETPUBLICATIONORDER='SETPUBLICATIONORDER';

